### ISSUE TITLE
register service error:does not have associated TTL

### ISSUE THREAD

**Issue by kinofrally** [oliora/ppconsul#13]
Hi Andrey,

I have encountered really weird problem when using ppconsul library.

When my app register to consul server with httpcheck, it always get  below error.

(CheckID "service:my-service:XX.XX.XX.Xx:8012" does not have associated TTL [500 Internal Server Error]

and consul server print below error log:

"[ERR] http: Request PUT /v1/agent/check/pass/service%3Amy-service%3A10.237.81.111%3A8012, error: CheckID "service:my-service:XX.XX.XX.XX:8012" does not have associated TTL from=XX.XX.XX.XX:55686" 

If I change to TTL check, it works fine. And I stop my service, change back to httpcheck, it magically don't have problem any more. At the whole time, consul server must stay up. If consul server restart, httpcheck will fail to register again.

So the problem is how can I register a service successfully with httpcheck at the first time?

Here is my httpcheck code:

agent.registerService(
			kw::name = "my-service",
			kw::port = 8012,
			kw::id = "my-service:8012",
                        kw::check = HttpCheck{"http://XX.XX.XX.XX:8012/health", std::chrono::seconds(60)}
		);

ttlcheck code:

 agent.registerService(
                        kw::name = "my-service",
			kw::port = 8012,
			kw::id = "my-service:8012",
                        kw::check = TtlCheck{std::chrono::seconds(6000)}
                );

And my consul server version is v1.0.2.

Look forward for your reply.

Thanks,
Vera

**Comment by oliora** [comment]
Hi Vera,

It's strange. I've just checked HTTP check over my local Consul v1.0.2 with the following code and it works just fine.

```
    using ppconsul::Consul;
    using namespace ppconsul::agent;

    Consul consul;
    Agent agent(consul);

    agent.registerService(
        kw::name = "my-service",
        kw::port = 9876,
        kw::id = "my-service:8012",
        kw::check = HttpCheck{"http://localhost:80/", std::chrono::seconds(2)}
    );
```

As I see from provided Consul log, the error you get is on updating check status not on registration (because of `PUT /v1/agent/check/pass/service%3Amy-service%3A10.237.81.111%3A8012`). Do you use both HTTP check and status update (`agent::pass()` or `agent.servicePass()` functions) together?

**Comment by kinofrally** [comment]
Yeah, it's true that I am using HTTP check and Agent::servicePass() for the same service. Now I only use HTTP check for my service, it worked fine. Thank you so much~~~

**Comment by oliora** [comment]
You welcome!
