### ISSUE TITLE
unique_ptr compile error with gcc

### ISSUE THREAD

**Issue by jgornowich** [oliora/ppconsul#17]
Pulling the most recent changes I have encountered a compiler error on my linux development machine running gcc Ubuntu 5.4.0 with the following error: 

> src/curl/http_client.h: error: 'unique_ptr' in namespace 'std' does not name a template type std::unique_ptr<CURL, detail::CurlEasyDeleter> m_handle;

Compiling on my OSX machine does not show any errors.  After a quick debug I have found that putting `#include <memory>` in http_client.h resolves my linux compile issue.  Should I just make a PR for this?

**Comment by oliora** [comment]
It should be already fixed in https_client branch which I’ll merge soon. But if you need a fix ASAP then please do.

**Comment by oliora** [comment]
I've merged HTTPS branch to master including the missing  `<memory>` fix. It should be fine now.
