### ISSUE TITLE
test failures with consul 1.0.3+

### ISSUE THREAD

**Issue by CJLove** [oliora/ppconsul#21]
With consul 1.0.3+ there are test failures likely due to this change made in the 1.0.3 release: https://github.com/hashicorp/consul/issues/3762

Typical failure:
```
/Users/cl186051/Consul/ppconsul/tests/agent/agent_checks_tests.cpp:169: FAILED:
due to unexpected exception with message:
  400 Bad Request
```

**Comment by oliora** [comment]
Thank you for reporting this and for the investigation. I’ll fix it soo. In The meanwhile if the only failed test is “agent.check_registration_special_chars” (or any other special chars test) it’s safe to go with current ppconsul version. Thoose tests are only test the Consul accepts special characters in various APIs but apparently it’s not a case now.

**Comment by oliora** [comment]
Obsolete tests are removed
