### ISSUE TITLE
error LNK2001: unresolved external symbol while trying to build the project

### ISSUE THREAD

**Issue by rprasanakumar** [oliora/ppconsul#24]
Hello,

I'm a beginner to cpp and trying to use a cpp library called ppconsul(https://github.com/oliora/ppconsul ). This library has dependency to some of other libraries like (boost and curl). I have build ppconsul with all its dependencies and trying to use ppconsul executable in a new project. When I try to build the new project, I'm getting some linker issue like below.

error LNK2001: unresolved external symbol "public: virtual char const * thiscall ppconsul::BadStatus::what(void)const " (?what@BadStatus@ppconsul@@UBEPBDXZ) 1>ConsulApp.obj : error LNK2019: unresolved external symbol "class std::basic_string,class std::allocator > __cdecl ppconsul::helpers::encodeUrl(class std::basic_string,class std::allocator > const &)" (?encodeUrl@helpers@ppconsul@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z) referenced in function "void __cdecl ppconsul::parameters::detail::printParameter(class std::basic_ostream > &,class std::basic_string,class std::allocator > const &,struct ppconsul::kw::dc_keyword)" (??$printParameter@Udc_keyword__@kw@ppconsul@@@detail@parameters@ppconsul@@YAXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@Udc_keyword__@kw@2@@Z)

I tried to link the project and change the visual studio but nothing worked. Anybody has any idea about this linker issue? TIA, Prassi

**Comment by oliora** [comment]
I’ll take a look. If you don’t mind you can build a ppconsul as a static library by passing `-DBUILD_STATIC_LIB=ON` to CMake. This should solve your issue.

**Comment by rprasanakumar** [comment]
@oliora Thank you so much for your response. I tried to build It this way. But, still it did not help me out.

**Comment by oliora** [comment]
What error do you get when you link with ppconsul static library?

**Comment by rprasanakumar** [comment]
I'm getting the same set of errors like below,

1>ConsulConnect.obj : error LNK2001: unresolved external symbol "public: virtual char const * __thiscall ppconsul::BadStatus::what(void)const " (?what@BadStatus@ppconsul@@UBEPBDXZ)
1>ConsulConnect.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ppconsul::helpers::encodeUrl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?encodeUrl@helpers@ppconsul@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z) referenced in function "void __cdecl ppconsul::parameters::detail::printParameter<struct ppconsul::kw::dc_keyword__>(class std::basic_ostream<char,struct std::char_traits<char> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct ppconsul::kw::dc_keyword__)" (??$printParameter@Udc_keyword__@kw@ppconsul@@@detail@parameters@ppconsul@@YAXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@Udc_keyword__@kw@2@@Z)
1>ConsulConnect.obj : error LNK2019: unresolved external symbol "private: __thiscall ppconsul::Consul::Consul(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct ppconsul::http::impl::TlsConfig const &)" (??0Consul@ppconsul@@AAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00ABUTlsConfig@impl@http@1@@Z) referenced in function "public: __thiscall ppconsul::Consul::Consul<,void>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$?0$$VX@Consul@ppconsul@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ConsulConnect.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ppconsul::agent::impl::serviceRegistrationJson(struct ppconsul::agent::impl::ServiceRegistrationData const &)" (?serviceRegistrationJson@impl@agent@ppconsul@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABUServiceRegistrationData@123@@Z) referenced in function "public: void __thiscall ppconsul::agent::Agent::registerService<struct boost::fusion::pair<struct ppconsul::agent::kw::name_keyword__,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,void>(struct boost::fusion::pair<struct ppconsul::agent::kw::name_keyword__,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > &&)" (??$registerService@U?$pair@Uname_keyword__@kw@agent@ppconsul@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@fusion@boost@@X@Agent@agent@ppconsul@@QAEX$$QAU?$pair@Uname_keyword__@kw@agent@ppconsul@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@fusion@boost@@@Z)

**Comment by oliora** [comment]
You should not get it when you build ppconsul as static library. Probably previous CMake generated settings are stuck so you need to start from scratch. Please do the following and if you got an error provide me with *complete* console output for the whole process.

1. `cd <ppconsul_dir>` (<ppconsul_dir> is a dir where ppcosnul is checked out)
1. `mkdir build-static` (note that it's essential to start with empty directory rather than do stuff in directory where CMake has been already invoked)
1. `cd build-static`
1. Configure ppconsul to build static library: `cmake -DBUILD_STATIC_LIB=ON ..` (you might also need to provide Visual Studio generator and path to Boost and libcurl)
1. Build ppconsul: `cmake --build . --config Release`

Now you can build your project that depends on ppconsul:
1. Modify your project's CMake file to have the following:
    ```
    find_package(ppconsul REQUIRED)
    target_link_libraries(<your_target_that_depends_on_ppcosnul> ppconsul)
    ```
1. Configure your project with providing a correct path to ppconsul: `cmake -Dppconsul_DIR=<ppconsul_dir>/build ...` ("..." is all other CMake options that your project needs)
1. Build your project in a normal way

**Comment by rprasanakumar** [comment]
@oliora Thank you so much for your help. The issue got resolved when I started the cmake build from the scratch. Thank you again. I have a small suggestion to add ppconsul to vcpkg(https://github.com/Microsoft/vcpkg). In this way, we can make the ppconsul readily available to use in Visual Studio projects through vcpkg. Thoughts?  
Best,
Prassi

**Comment by oliora** [comment]
I've created a ticket to fix ppcosnul build on Windows: https://github.com/oliora/ppconsul/issues/25
