### ISSUE TITLE
Add support for service metadata

### ISSUE THREAD

**Issue by ahtur** [oliora/ppconsul#29]
Hello. Doesn't the library support service-specific metadata (https://www.consul.io/api/agent/service.html#meta) or is there a way to assign metadata to a service after registering it ?

**Comment by oliora** [comment]
No, neither getting or setting metadata is not supported but it should be easy to add this feature if needed.

**Comment by ahtur** [comment]
> No, neither getting or setting metadata is not supported but it should be easy to add this feature if needed.
Thanks for your quick answer. I was planning to use that feature so don't hesitate to add it if you can, it's a standard feature of Consul and other libraries support it. Other than that, congratulations for this helpful library.

**Comment by oliora** [comment]
Both registering service with metadata and retrieving one is supported.

**Comment by ahtur** [comment]
Thank you very much. I'll give it a try this week.
