### ISSUE TITLE
Could remove the dependency of boost?

### ISSUE THREAD

**Issue by NickYang1988** [oliora/ppconsul#33]
Could remove the dependency of boost in header files?

**Comment by oliora** [comment]
This is not possible for several reasons:
1. Keyword arguments library is build with using of Boost.MPL and Boost.Fusion.
2. Vocabulary types Boost.Optional, Boost.Variant and Boost.StringRef are extensively used in headers.

To get rid of Boost dependency in headers one has to rewrite keywords library with another MPL library and rewrite Ppconsul to use before-mentioned vocabulary types from either C++17 or from some third-party libraries.

Overall, I’m completely for getting rid of Boost in favor of C++17 and some modern lightweight MPL library but that’s quite some work.

**Comment by oliora** [comment]
The issue was closed by mistake so I’m reopening it.

**Comment by NickYang1988** [comment]
Thanks for the reply, I get it.
