### ISSUE TITLE
Default redhat 7 curl version not comptible

### ISSUE THREAD

**Issue by jgornowich** [oliora/ppconsul#38]
Recent additions for adding support to abort pending requests (b75b801e9acc2c79b29f397a85e27e21a00af776) introduced curl symbols `CURLOPT_XFERINFOFUNCTION` and `CURLOPT_XFERINFODATA` which were introduced with curl 7.32.0 release.  Redhat 7 default package for curl is version 7.29 which causes a failure to build. 

This is not affecting me personally, however I wanted to create an issue for anyone else that may come across a this problem.  It's probably worth just updating the readme to specify a version for the lib curl dependency that is required?

**Comment by oliora** [comment]
I’ll check whether is it possible to detect Curl version at compile time and try to make the abortion support optional. If not then I’ll set the correct required version of Curl in CMakeLists

**Comment by oliora** [comment]
Should be fixed now. Please reopen if not.
