### ISSUE TITLE
kv-test unit test fails

### ISSUE THREAD

**Issue by zapbranighan** [oliora/ppconsul#5]
Running Ubuntu 16.04 on a VMware instance (virtual machine) on my Macbook Pro.

Running Consul version v0.7.2

I started consul with command: consul agent -dev

Result of running kv-tests:

===============================================================================
test cases: 10 |  2 passed |  8 failed
assertions: 75 | 56 passed | 19 failed

**Comment by oliora** [comment]
@zapbranighan could you please verify that tests are now passing with Consul v7?

**Comment by zapbranighan** [comment]
Latest commit now passes KV unit test:

normin@ubuntu:~/workspace/ppconsul/build/output$ ./kv-tests 
===============================================================================
All tests passed (398 assertions in 10 test cases)


Awesome!
