### ISSUE TITLE
Question about adding ppconsul library to my cmake project

### ISSUE THREAD

**Issue by zapbranighan** [oliora/ppconsul#6]
Hi Andrey,

I ran into you git project (https://github.com/oliora/ppconsul) when I googled 'consul c++ client'.

I wanted to play around with the client that you wrote. However I'm having trouble creating a simple cmake project to link with your library.

Here is what is in main.cpp:

```cpp
#include <iostream>
#include "ppconsul/agent.h"

int main(int argc, char const *argv[]) {
  using namespace ppconsul;

  // Create a consul client with using of a default address ("127.0.0.1:8500") and default DC
  Consul consul;
  // We need the 'agent' endpoint for a service registration
  agent::Agent agent(consul);

  return 0;
}
```

Very basic stuff. Here is what my simple CMakeList.txt looks like:

```
cmake_minimum_required(VERSION 2.8)

project(consuldemo)

#Enable C++14
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED on)

#On g++ this ensures -std=c++11 and not -std=gnu++11
set(CMAKE_CXX_EXTENSIONS OFF)

include_directories ("${PROJECT_SOURCE_DIR}/ppconsul/include")

FIND_PACKAGE(CURL)
IF(CURL_FOUND)
  MESSAGE(STATUS "Curl libraries found at: ${CURL_LIBRARIES}")
  MESSAGE(STATUS "Curl includes found at: ${CURL_INCLUDE_DIRS}")
else()
  MESSAGE(SEND_ERROR "Could not find cURL on your system")
ENDIF(CURL_FOUND)


add_executable(consuldemo main.cpp)

# set the path to the library folder. libppconsul.a is in /usr/local/lib
link_directories(/usr/local/lib)

target_link_libraries(consuldemo ${CURL_LIBRARIES} json11 ppconsul)
```

I'm having trouble in the link phase:

```
//usr/local/lib/libppconsul.a(http_client.cpp.o): In function `ppconsul::curl::(anonymous namespace)::CurlInitializer::CurlInitializer()':
http_client.cpp:(.text+0xb0): undefined reference to `curl_global_init'
....
....
```

Can you please suggest a best practice simple hello world type CMakeList.txt project which can link against libppconsul.a?

I am able to build the ppconsul cmake project fine so I should have curl installed properly. My cmake project is probably not correct.

Thanks in advance for any help you can provide.

Thanks,
Normin

**Comment by oliora** [comment]
Hi Normin,

Seems that CMake can't find `libcurl` library. Could you please post the full output of CMake and Make commands. Before running the CMake command make sure to clean the workspace directory thus CMake can't pickup cached variables and paths.
To make sure `libcurl` is found change the find command to `FIND_PACKAGE(CURL REQUIRED)`.

**Comment by oliora** [comment]
This slightly changed `CMakeLists.txt` works fine for me:

```cmake
cmake_minimum_required(VERSION 3.0)

project(consuldemo)

#Enable C++14
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED on)

#On g++ this ensures -std=c++11 and not -std=gnu++11
set(CMAKE_CXX_EXTENSIONS OFF)

FIND_PACKAGE(Boost 1.55 REQUIRED)
FIND_PACKAGE(CURL REQUIRED)

# PPConsul "finder"
set(PPCONSUL_INCLUDE_DIRS "$ENV{HOME}/projects/ppconsul/include")    # Replace with your path to ppconsul includes
set(PPCONSUL_LIBRARIES_DIR "$ENV{HOME}/projects/ppconsul/ws/output") # Replace with your path to ppconsul library
find_library(PPCONSUL_JSON11_LIB json11 HINTS ${PPCONSUL_LIBRARIES_DIR})
find_library(PPCONSUL_PPCONSUL_LIB ppconsul HINTS ${PPCONSUL_LIBRARIES_DIR})
set(PPCONSUL_LIBRARIES "${PPCONSUL_JSON11_LIB}" "${PPCONSUL_PPCONSUL_LIB}")

add_executable(consuldemo main.cpp)

target_include_directories(consuldemo PRIVATE
    "${Boost_INCLUDE_DIRS}"
    "${CURL_INCLUDE_DIRS}"
    "${PPCONSUL_INCLUDE_DIRS}"
)

target_link_libraries(consuldemo ${CURL_LIBRARIES} ${PPCONSUL_LIBRARIES})
```

This works fine on macOS.

**Comment by zapbranighan** [comment]
I am trying to build on a Linux Ubuntu 16.04 platform.

I am still hitting the same issue after applying the CMakeLists.txt changes you suggested.

Here is the output:

n.emralino@ssna-eng-a1-stor7:/workspace/normin/consuldemo/build$ cmake -G "Unix Makefiles" ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.63.0
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/normin/consuldemo/build
n.emralino@ssna-eng-a1-stor7:/workspace/normin/consuldemo/build$
n.emralino@ssna-eng-a1-stor7:/workspace/normin/consuldemo/build$
n.emralino@ssna-eng-a1-stor7:/workspace/normin/consuldemo/build$ make
Scanning dependencies of target consuldemo
[ 50%] Building CXX object CMakeFiles/consuldemo.dir/main.cpp.o
[100%] Linking CXX executable consuldemo
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `ppconsul::curl::(anonymous namespace)::CurlInitializer::CurlInitializer()':
http_client.cpp:(.text+0xb0): undefined reference to `curl_global_init'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `ppconsul::curl::(anonymous namespace)::CurlInitializer::~CurlInitializer()':
http_client.cpp:(.text+0xcf): undefined reference to `curl_global_cleanup'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `ppconsul::curl::HttpClient::HttpClient()':
http_client.cpp:(.text+0x9db): undefined reference to `curl_easy_init'
http_client.cpp:(.text+0xa41): undefined reference to `curl_easy_setopt'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `ppconsul::curl::HttpClient::~HttpClient()':
http_client.cpp:(.text+0xb53): undefined reference to `curl_easy_cleanup'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `ppconsul::curl::HttpClient::perform()':
http_client.cpp:(.text._ZN8ppconsul4curl10HttpClient7performEv[_ZN8ppconsul4curl10HttpClient7performEv]+0x18): undefined reference to `curl_easy_perform'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `void ppconsul::curl::HttpClient::setopt<CURLoption, long>(CURLoption, long const&)':
http_client.cpp:(.text._ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionlEEvT_RKT0_[_ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionlEEvT_RKT0_]+0x30): undefined reference to `curl_easy_setopt'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `void ppconsul::curl::HttpClient::setopt<CURLoption, unsigned long (*)(char*, unsigned long, unsigned long, void*)>(CURLoption, unsigned long (* const&)(char*, unsigned long, unsigned long, void*))':
http_client.cpp:(.text._ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionPFmPcmmPvEEEvT_RKT0_[_ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionPFmPcmmPvEEEvT_RKT0_]+0x30): undefined reference to `curl_easy_setopt'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `void ppconsul::curl::HttpClient::setopt<CURLoption, decltype(nullptr)>(CURLoption, decltype(nullptr) const&)':
http_client.cpp:(.text._ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionDnEEvT_RKT0_[_ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionDnEEvT_RKT0_]+0x2e): undefined reference to `curl_easy_setopt'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `void ppconsul::curl::HttpClient::setopt<CURLoption, char const*>(CURLoption, char const* const&)':
http_client.cpp:(.text._ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionPKcEEvT_RKT0_[_ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionPKcEEvT_RKT0_]+0x30): undefined reference to `curl_easy_setopt'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o): In function `void ppconsul::curl::HttpClient::setopt<CURLoption, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*>(CURLoption, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* const&)':
http_client.cpp:(.text._ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvT_RKT0_[_ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvT_RKT0_]+0x30): undefined reference to `curl_easy_setopt'
/workspace/normin/ppconsul/workspace/output/libppconsul.a(http_client.cpp.o):http_client.cpp:(.text._ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionPSt5tupleIJNS_4http6StatusENS_15ResponseHeadersENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEEEvT_RKT0_[_ZN8ppconsul4curl10HttpClient6setoptI10CURLoptionPSt5tupleIJNS_4http6StatusENS_15ResponseHeadersENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEEEvT_RKT0_]+0x30): more undefined references to `curl_easy_setopt' follow
collect2: error: ld returned 1 exit status
CMakeFiles/consuldemo.dir/build.make:97: recipe for target 'consuldemo' failed
make[2]: *** [consuldemo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/consuldemo.dir/all' failed
make[1]: *** [CMakeFiles/consuldemo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have also attached my CMakeLists.txt and main.cpp
[Desktop.zip](https://github.com/oliora/ppconsul/files/720126/Desktop.zip)

I will try on my Macbook tomorrow.

**Comment by oliora** [comment]
Hm, strange. I'll find my Ubuntu machine and try to reproduce the error.

**Comment by oliora** [comment]
I did not tried to build on Linux but I'm pretty sure it's about the order if linked libraries which matters on Linux and doesn't matter on macOS.

Could you please try to change the order of link liibraries to put Curl afer Ppconsul: `target_link_libraries(consuldemo ${PPCONSUL_LIBRARIES} ${CURL_LIBRARIES})`. Also, json11 should be linked after Ppconsul: `set(PPCONSUL_LIBRARIES "${PPCONSUL_PPCONSUL_LIB}" "${PPCONSUL_JSON11_LIB}")`

**Comment by oliora** [comment]
I'm thinking about changing Ppconsul into a dynamic library to hide all the dependencies and linking comexity inside the library. Does using of Ppconsul as a dynamic library sounds ok for you?

**Comment by zapbranighan** [comment]
Changing the linking order worked :)
Here is the order I used:
target_link_libraries(consuldemo ${PPCONSUL_JSON11_LIB} ${PPCONSUL_PPCONSUL_LIB} ${Boost_LIBRARIES} ${CURL_LIBRARIES})

**Comment by zapbranighan** [comment]
I also just noticed that the correct link order should be:

target_link_libraries(consuldemo ${PPCONSUL_PPCONSUL_LIB} ${PPCONSUL_JSON11_LIB} ${Boost_LIBRARIES} ${CURL_LIBRARIES})

As you suggested. This order also worked.

Thanks for the help Andrey!

**Comment by oliora** [comment]
You welcome!
