### ISSUE TITLE
No debug symbols installed on Windows

### ISSUE THREAD

**Issue by ppietrasa** [oliora/ppconsul#61]
When building the ppconsul with "CMAKE_BUILD_TYPE=Debug" or "CMAKE_BUILD_TYPE=RelWithDebInfo". It would be good to have the .pdb (debug symbols) installed along the lib file.  Otherwise, the user of the library is confronted with MSVC warnings about the missing .pdb.

In ppconsul this could be achieved so:
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index c1a0dd8..cff80ce 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -87,6 +87,8 @@ source_group(libb64 FILES ${LIBB64_SOURCES})
 set_target_properties(${PROJECT_NAME} PROPERTIES
     VERSION ${Ppconsul_VERSION}
     SOVERSION ${Ppconsul_VERSION}
+    COMPILE_PDB_NAME ${PROJECT_NAME}
+    COMPILE_PDB_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
     FOLDER ${PROJECT_NAME}
 )

@@ -97,4 +99,11 @@ install(
     ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
     RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
 )
+if(WIN32)
+    install(
+        FILES ${COMPILE_PDB_OUTPUT_DIRECTORY}/${PROJECT_NAME}.pdb
+        DESTINATION "${CMAKE_INSTALL_LIBDIR}"
+        OPTIONAL
+    )
+endif()
```

Note: The `ïnstall` of the `ppconsul.pdb` is optional, in case e.g. CMAKE_BUILD_TYPE=Release is configured, and no .pdb created.

**Comment by ppietrasa** [comment]
Another alternative to the above would be to pass "/Z7" instead of "/Zi" to the compiler, thus burning the debug symbols inside the .lib. This requires some postprocessing / tuning of the CMAKE_CXX_FLAGS_DEBUG or CMAKE_CXX_FLAGS_RELWITHDEBINFO flags or some other cmake variable. I think there's more than one way to do this.  I guess, installation of the pdb is a more straightforward way to get rid of the error.

**Comment by oliora** [comment]
I agree that installing pdb is a better option than mangling the standard CMake flags.

Could you possibly send a pull request with the changes above?
