### ISSUE TITLE
mutil thread watch key, libcurl segmentation fault

### ISSUE THREAD

**Issue by cc20110101** [oliora/ppconsul#65]
![image](https://user-images.githubusercontent.com/12064991/146136872-ab8d6c0b-c56f-4f11-9818-9487e8cf5c4c.png)

**Comment by oliora** [comment]
Hi @cc20110101, thank you for the issue. 

To make it possible to found the root cause please provide the following:
1. Your platform (OS and compiler)
2. Version of libcurl
2. Version of ppconsul
3. Minimal example that cause the segfault

If the last item is not feasible then at least describe the way how you use Ppconsul from multiple threads.

**Comment by cc20110101** [comment]
CentOS Linux release 7.7.1908 (Core)
CentOS Linux release 7.6.1810 (Core) 
Curl and libcurl 7.49.0
Ppconsul *Version 0.2.2*

**Comment by cc20110101** [comment]
void listenConsulKey() {
    new std::thread(
        [&] {
            try {
                pthread_setname_np(pthread_self(), "csKeyProperty");
                std::string consulAddr = utility::Concat(Config::instance().consul_.ipv4, ":", Config::instance().consul_.port);
                std::string key = utility::Concat("ivideo/dcg-test/", Config::instance().service_uid_, "/property");
                ppconsul::Consul consul(consulAddr, ppconsul::kw::dc = "dc1");
                ppconsul::kv::Kv kv(consul);
                while (1) {
                    try {
                        ppconsul::kv::KeyValue item = kv.item(key);
                        item = kv.item(key, ppconsul::kv::kw::block_for = {std::chrono::minutes(1), item.modifyIndex});
                    } catch (const std::exception &e) {
                        Error("consul exception: %s", e.what());
                    }
                }
            } catch (const std::exception &e) {
                Error("consul exception: %s", e.what());
            }
        }
    );

    new std::thread(
        [&] {
            try {
                pthread_setname_np(pthread_self(), "csKeyDomain");
                std::string consulAddr = utility::Concat(Config::instance().consul_.ipv4, ":", Config::instance().consul_.port);
                std::string key = utility::Concat("ivideo/dcg-test/", Config::instance().service_uid_, "/domain");
                ppconsul::Consul consul(consulAddr, ppconsul::kw::dc = "dc1");
                ppconsul::kv::Kv kv(consul);
                while (1) {
                    try {
                        ppconsul::kv::KeyValue item = kv.item(key);
                        item = kv.item(key, ppconsul::kv::kw::block_for = {std::chrono::minutes(1), item.modifyIndex});
                    } catch (const std::exception &e) {
                        Error("consul exception: %s", e.what());
                    }
                }
            } catch (const std::exception &e) {
                Error("consul exception: %s", e.what());
            }
        }
    );

    new std::thread(
        [&] {
            try {
                pthread_setname_np(pthread_self(), "csKeyRabbitmq");
                std::string consulAddr = utility::Concat(Config::instance().consul_.ipv4, ":", Config::instance().consul_.port);
                std::string key = "middleware/rabbitmq";
                ppconsul::Consul consul(consulAddr, ppconsul::kw::dc = "dc1");
                ppconsul::kv::Kv kv(consul);
                while (1) {
                    try {
                        ppconsul::kv::KeyValue item = kv.item(key);
                        item = kv.item(key, ppconsul::kv::kw::block_for = {std::chrono::minutes(1), item.modifyIndex});
                    } catch (const std::exception &e) {
                        Error("consul exception: %s", e.what());
                    }
                }
            } catch (const std::exception &e) {
                Error("consul exception: %s", e.what());
            }
        }
    );

    new std::thread(
        [&] {
            try {
                pthread_setname_np(pthread_self(), "csKeyKong");
                std::string consulAddr = utility::Concat(Config::instance().consul_.ipv4, ":", Config::instance().consul_.port);
                std::string key = "middleware/kong";
                ppconsul::Consul consul(consulAddr, ppconsul::kw::dc = "dc1");
                ppconsul::kv::Kv kv(consul);
                while (1) {
                    try {
                        ppconsul::kv::KeyValue item = kv.item(key);
                        item = kv.item(key, ppconsul::kv::kw::block_for = {std::chrono::minutes(1), item.modifyIndex});
                    } catch (const std::exception &e) {
                        Error("consul exception: %s", e.what());
                    }
                }
            } catch (const std::exception &e) {
                Error("consul exception: %s", e.what());
            }
        }
    );
}


int mina() {
    listenConsulKey();
    while (true) {
        std::this_thread::sleep_for(std::chrono::seconds(10));
    }

}

**Comment by cc20110101** [comment]
`
void listenConsulKey() {
    new std::thread(
        [&] {
            try {
                pthread_setname_np(pthread_self(), "csKeyProperty");
                std::string consulAddr = utility::Concat(Config::instance().consul_.ipv4, ":", Config::instance().consul_.port);
                std::string key = utility::Concat("ivideo/dcg-test/", Config::instance().service_uid_, "/property");
                ppconsul::Consul consul(consulAddr, ppconsul::kw::dc = "dc1");
                ppconsul::kv::Kv kv(consul);
                while (1) {
                    try {
                        ppconsul::kv::KeyValue item = kv.item(key);
                        item = kv.item(key, ppconsul::kv::kw::block_for = {std::chrono::minutes(1), item.modifyIndex});
                    } catch (const std::exception &e) {
                        Error("consul exception: %s", e.what());
                    }
                }
            } catch (const std::exception &e) {
                Error("consul exception: %s", e.what());
            }
        }
    );

    new std::thread(
        [&] {
            try {
                pthread_setname_np(pthread_self(), "csKeyDomain");
                std::string consulAddr = utility::Concat(Config::instance().consul_.ipv4, ":", Config::instance().consul_.port);
                std::string key = utility::Concat("ivideo/dcg-test/", Config::instance().service_uid_, "/domain");
                ppconsul::Consul consul(consulAddr, ppconsul::kw::dc = "dc1");
                ppconsul::kv::Kv kv(consul);
                while (1) {
                    try {
                        ppconsul::kv::KeyValue item = kv.item(key);
                        item = kv.item(key, ppconsul::kv::kw::block_for = {std::chrono::minutes(1), item.modifyIndex});
                    } catch (const std::exception &e) {
                        Error("consul exception: %s", e.what());
                    }
                }
            } catch (const std::exception &e) {
                Error("consul exception: %s", e.what());
            }
        }
    );

    new std::thread(
        [&] {
            try {
                pthread_setname_np(pthread_self(), "csKeyRabbitmq");
                std::string consulAddr = utility::Concat(Config::instance().consul_.ipv4, ":", Config::instance().consul_.port);
                std::string key = "middleware/rabbitmq";
                ppconsul::Consul consul(consulAddr, ppconsul::kw::dc = "dc1");
                ppconsul::kv::Kv kv(consul);
                while (1) {
                    try {
                        ppconsul::kv::KeyValue item = kv.item(key);
                        item = kv.item(key, ppconsul::kv::kw::block_for = {std::chrono::minutes(1), item.modifyIndex});
                    } catch (const std::exception &e) {
                        Error("consul exception: %s", e.what());
                    }
                }
            } catch (const std::exception &e) {
                Error("consul exception: %s", e.what());
            }
        }
    );

    new std::thread(
        [&] {
            try {
                pthread_setname_np(pthread_self(), "csKeyKong");
                std::string consulAddr = utility::Concat(Config::instance().consul_.ipv4, ":", Config::instance().consul_.port);
                std::string key = "middleware/kong";
                ppconsul::Consul consul(consulAddr, ppconsul::kw::dc = "dc1");
                ppconsul::kv::Kv kv(consul);
                while (1) {
                    try {
                        ppconsul::kv::KeyValue item = kv.item(key);
                        item = kv.item(key, ppconsul::kv::kw::block_for = {std::chrono::minutes(1), item.modifyIndex});
                    } catch (const std::exception &e) {
                        Error("consul exception: %s", e.what());
                    }
                }
            } catch (const std::exception &e) {
                Error("consul exception: %s", e.what());
            }
        }
    );
}


int mina() {
    listenConsulKey();
    while (true) {
        std::this_thread::sleep_for(std::chrono::seconds(10));
    }

}`

**Comment by cc20110101** [comment]
example code
[test.txt](https://github.com/oliora/ppconsul/files/7717394/test.txt)

**Comment by cc20110101** [comment]
Happens occasionally

**Comment by oliora** [comment]
Can you add change the code as following and rerun yhr example?

1. Add this as the first command in `main` (before any thread is started):
```
curl_global_init(CURL_GLOBAL_DEFAULT | CURL_GLOBAL_SSL);
```
2. Add this as the last command in `main` (after all threads are stopped):
```
curl_global_cleanup();
```

**Comment by oliora** [comment]
@cc20110101 please let me know whether the issue is fixed or not

**Comment by cc20110101** [comment]
There is no segfault, but it still exits abnormally

**Comment by oliora** [comment]
What exactly do you mean? Does the example abnormally aborts while it is running, or, when signaled to exit it does not do a clean shutdown?

**Comment by cc20110101** [comment]
TTL heartbeat timeout, add the crul timeout parameter; after removing the curl timeout parameter and adding curl_global_init, there is no problem for three days

**Comment by cc20110101** [comment]
TTL heartbeat is sometimes blocked, add the crul timeout parameter; after removing the curl timeout parameter and adding curl_global_init, there is no problem for three days

**Comment by cc20110101** [comment]
The curl library was compiled without the parameter --enable-ares

**Comment by oliora** [comment]
It’s good that it’s stable now. I don’t get the part about removing curl timeout parameter. Is it a change to ppconsul that need to be done to make example work?

**Comment by cc20110101** [comment]
ppconsul has the problem of heartbeat blocking in ttl reporting. The put method of curl adds the timeout parameter setting setopt (CURLOPT_TIMEOUT, 5l) to solve it, but multi-threading will cause segmentation errors.

**Comment by cc20110101** [comment]
![image](https://user-images.githubusercontent.com/12064991/146902165-5da62d8f-7bea-4e3d-bf57-b06516e8efa5.png)

**Comment by oliora** [comment]
Sorry, can you clarify? Did you mean that in your case adding timeout parameter was required to stop segfaulting? Was it segfaulting on application shutdown or just during normal execution?

**Comment by cc20110101** [comment]
The service is a resident process, and will not exit the service under normal circumstances, unless there is an exception or a segmentation fault.
1. ppconsul does not set the curl timeout parameter, and the thread will be stuck when the heartbeat is reported in ttl mode;
2. Modify the ppconsul library and set the curl timeout parameter. Multithreading will cause segmentation errors;
3. Compile the curl library. Use the c-ares library to enable dns asynchronous parsing, and add curl timeout when modifying ppconsul, everything is normal;

**Comment by oliora** [comment]
Thank you very much for detailed info!

This very much looks like libcurl’s intended behavior. [CURLOPT_TIMEOUT](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html) and [CURLOPT_NOSIGNAL](https://curl.se/libcurl/c/CURLOPT_NOSIGNAL.html) says that setting this parameter will cause libcurl to send SIGALRM signal to abort transfer unless asynchronous DNS resolver like c-ares is used. I’m pretty sure that on step 2 you receive SiGALRM (14) rather than any other signal (would be great if you can confirm this). I will add timeout parameter to `Consul` object parameters, just need to figure out what’s best to do with signaling behavior of libcurl.

**Comment by oliora** [comment]
Pushed change that allows to setup connect and request timeout
