### ISSUE TITLE
Add client application example

### ISSUE THREAD

**Issue by oliora** [oliora/ppconsul#7]
- It should be possible to do `make install` and get Ppconsul installed system-wide.
- Add client application example (source + CMake config).

**Comment by ik-wg** [comment]
CMake config now supports make install (only builds/installs static libs)

**Comment by oliora** [comment]
Now ppconsul can be installed (either as dynamic or static library). Readme covers installation and usage. Only an example of client app is left.

**Comment by oliora** [comment]
There is a CMake example on how to configure such an application. I think this is enough
