### ISSUE TITLE
Failed to connect to 127.0.0.1 port 8500: Connection refused (7)

### ISSUE THREAD

**Issue by LapinDeNeige** [oliora/ppconsul#73]
Trying to run example 

 `Consul con;
  Agent ag(con);
  ag.registerService(
  name="my-service",
  port=18747,
   check=TtlCheck{std::chrono::seconds(5)}
`
After what I always get Error Message

`terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to connect to 127.0.0.1 port 8500: Connection refused (7)
Aborted (core dumped)
 `

**Comment by indev29** [comment]
Do you have your [consul agent](https://www.consul.io/docs/agent) started?  
By default, it should be running on the same host as the example, the simplest way is to do `consul agent -dev`.

**Comment by LapinDeNeige** [comment]
I ran consul agent -dev
Now after running example it gives out
`terminate called after throwing an instance of 'ppconsul::BadStatus'
  what():  method GET not allowed [405 Method Not Allowed]
Aborted (core dumped)`

**Comment by LapinDeNeige** [comment]
As far as I understand I need to use PUT method to register service

**Comment by indev29** [comment]
Could you provide minimal reproducible example?

**Comment by LapinDeNeige** [comment]
Firstly as it was adviced I run consul agent 
`consul agent -dev`
then I compile by running make, it's OK
then I run programm  and it  gives out

`terminate called after throwing an instance of 'ppconsul::BadStatus' what(): method GET not allowed [405 Method Not Allowed] Aborted (core dumped)`

**Comment by LapinDeNeige** [comment]
Agent service gives out
`2022/03/17 10:38:25 [DEBUG] http: Request GET /v1/agent/check/pass/service%3Aname (40.879µs) from=127.0.0.1:38554
    2022/03/17 10:38:25 [WARN] agent: Check "service:my-service" HTTP request failed: Get http://localhost:80/: dial tcp 127.0.0.1:80: connect: connection refused
    2022/03/17 10:38:27 [WARN] agent: Check "service:my-service" HTTP request failed: Get http://localhost:80/: dial tcp 127.0.0.1:80: connect: connection refused
`

**Comment by LapinDeNeige** [comment]
I found here
https://github.com/hashicorp/consul/issues/3659

I need to use PUT method, how could I do that?

**Comment by indev29** [comment]
> I found here [hashicorp/consul#3659](https://github.com/hashicorp/consul/issues/3659)
> 
> I need to use PUT method, how could I do that?


You don't need to worry about that, the library does it for you. Could you please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

**Comment by LapinDeNeige** [comment]
#include "ppconsul/agent.h"

using ppconsul::Consul;
using namespace ppconsul::agent;

// Create a consul client that uses default local endpoint `http://127.0.0.1:8500` and default data center
Consul consul;
// We need the 'agent' endpoint for a service registration
Agent agent(consul);

// Register a service with associated HTTP check:
agent.registerService(
    kw::name = "my-service",
    kw::port = 9876,
    kw::tags = {"tcp", "super_server"},
    kw::check = HttpCheck{"http://localhost:80/", std::chrono::seconds(2)}
);

...

// Unregister service
agent.deregisterService("my-service");

**Comment by oliora** [comment]
@LapinDeNeige have you closed the issue because it works for you? If not, feel free to reopen.

**Comment by LapinDeNeige** [comment]
> 

I closed it because I don't need solution anymore as it is too late
