### ISSUE TITLE
Interruptable libcurl connecton

### ISSUE THREAD

**Issue by CodingTink** [oliora/ppconsul#9]
Hi,
I had the following issue:
I created a watcher object in a separate thread. The watcher made a blocking query on the Consul, and waited for changes.
Problem was on thread desctruction, the join() would wait on the blocking query.

I added a public method in the HttpClient to be able to cancel the request. In the libcurl implementation it is only a setopt(CURLOPT_TIMEOUT_MS, 1), but it seems to work fine.
I have done nothing for the netlib implementation though.

Should I submit a merge request ?

**Comment by oliora** [comment]
Hi,
I don't really get how you can abort an ongoing curl easy interface transfer (according to https://curl.haxx.se/docs/faq.html#How_do_I_stop_an_ongoing_transfe it's not possible) so please submit a pull request with a simple example of how you use it thus I can take a look.

**Comment by oliora** [comment]
Since there is no reply from the creator so far, I'm closing the issue.
